config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :pockets
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new
  	@exam = Exam.new
  end

  def create
  	exam = Exam.new(resource_params)
  	exam.save
  	flash[:notice] = 'New data has been created'
  	redirect_to exams_path
  end

  def edit
  	@exam = Exam.find(params[:id])
  end

  def update
  	@exam = Exam.find(params[:id])
  	@exam.update(resource_params)
  	flash[:notice] = 'The data has been updated'
  	redirect_to exams_path(@exam)
  end

  def destroy
  	@exam = Exam.find(params[:id])
  	@exam.destroy
  	flash[:notice] = 'The data has been deleted'
  	redirect_to exams_path
  end

  def index
  	@exams = Exam.all
  end

  def show
  	id = params[:id]
  	@exam = Exam.find(id)
  end

  private
  def resource_params
  	params.require(:exam).permit(:title, :mapel, :duration, :nilai, :status, :level, :student_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
  	@payment = Payment.new
  end

  def create
  	payment = Payment.new(resource_params)
  	payment.save
  	flash[:notice] = 'New data has been created'
  	redirect_to payments_path
  end

  def edit
  	@payment = Payment.find(params[:id])
  end

  def update
  	@payment = Payment.find(params[:id])
  	@payment.update(resource_params)
  	flash[:notice] = 'The data has been updated'
  	redirect_to payments_path(@payment)
  end

  def destroy
  	@payment = Payment.find(params[:id])
  	@payment.destroy
  	flash[:notice] = 'The data has been deleted'
  	redirect_to payments_path
  end

  def index
  	@payments = Payment.all
  end

  def show
  	id = params[:id]
  	@payment = Payment.find(id)
  end

  private
  def resource_params
  	params.require(:payment).permit(:id_transaction, :status, :upload)
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def new
  	@pocket = Pocket.new
  end

  def create
  	pocket = Pocket.new(resource_params)
  	pocket.save
  	flash[:notice] = 'New data has been created'
  	redirect_to pockets_path
  end

  def edit
  	@pocket = Pocket.find(params[:id])
  end

  def update
  	@pocket = Pocket.find(params[:id])
  	@pocket.update(resource_params)
  	flash[:notice] = 'The data has been updated'
  	redirect_to pockets_path(@pocket)
  end

  def destroy
  	@pocket = Pocket.find(params[:id])
  	@pocket.destroy
  	flash[:notice] = 'The data has been deleted'
  	redirect_to pockets_path
  end

  def index
  	@pockets = Pocket.all
  end

  def show
  	id = params[:id]
  	@pocket = Pocket.find(id)
  end

  private
  def resource_params
  	params.require(:pocket).permit(:balance, :student_id, :teacher_id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new
  	@report = Report.new
  end

  def create
  	report = Report.new(resource_params)
  	report.save
  	flash[:notice] = 'New data has been created'
  	redirect_to reports_path
  end

  def edit
  	@report = Report.find(params[:id])
  end

  def update
  	@report = Report.find(params[:id])
  	@report.update(resource_params)
  	flash[:notice] = 'The data has been updated'
  	redirect_to reports_path(@report)
  end

  def destroy
  	@report = Report.find(params[:id])
  	@report.destroy
  	flash[:notice] = 'The data has been deleted'
  	redirect_to reports_path
  end

  def index
  	@reports = Report.all
  end

  def show
  	id = params[:id]
  	@report = Report.find(id)
  end

  private
  def resource_params
  	params.require(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :date)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
  	@student = Student.new
  end

  def create
  	student = Student.new(resource_params)
  	student.save
  	flash[:notice] = 'New data has been created'
  	redirect_to students_path
  end

  def edit
  	@student = Student.find(params[:id])
  end

  def update
  	@student = Student.find(params[:id])
  	@student.update(resource_params)
  	flash[:notice] = 'The data has been updated'
  	redirect_to students_path(@student)
  end

  def destroy
  	@student = Student.find(params[:id])
  	@student.destroy
  	flash[:notice] = 'The data has been deleted'
  	redirect_to students_path
  end

  def index
  	@students = Student.all
  end

  def show
  	id = params[:id]
  	@student = Student.find(id)
  end

  private
  def resource_params
  	params.require(:student).permit(:name, :username, :age, :rombel, :address, :city, :nik)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
  	@teacher = Teacher.new
  end

  def create
  	teacher = Teacher.new(resource_params)
  	teacher.save
  	flash[:notice] = 'New data has been created'
  	redirect_to teachers_path
  end

  def edit
  	@teacher = Teacher.find(params[:id])
  end

  def update
  	@teacher = Teacher.find(params[:id])
  	@teacher.update(resource_params)
  	flash[:notice] = 'The data has been updated'
  	redirect_to teachers_path(@teacher)
  end

  def destroy
  	@teacher = Teacher.find(params[:id])
  	@teacher.destroy
  	flash[:notice] = 'The data has been deleted'
  	redirect_to teachers_path
  end

  def index
  	@teachers = Teacher.all
  end

  def show
  	id = params[:id]
  	@teacher = Teacher.find(id)
  end

  private
  def resource_params
  	params.require(:teacher).permit(:nik, :name, :age, :rombel, :mapel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |e| %>
	<%= e.label :title %></br>
	<%= e.text_field :title %></br>

	<%= e.label :subjects %></br>
	<%= e.text_field :mapel %></br>

	<%= e.label :duration %></br>
	<%= e.text_field :duration %></br>

	<%= e.label :score %></br>
	<%= e.text_field :nilai %></br>

	<%= e.label :status %></br>
	<%= e.text_field :status %></br>

	<%= e.label :level %></br>
	<%= e.text_field :level %></br>

	<%= e.label :student_id %></br>
	<%= e.text_field :student_id %></br>

	<%= e.submit %>
<% end %>

app/views/exams/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %>
</br>
<table>
	<tr>
		<td>Title</td>
		<td>Subjects</td>
		<td>Duration</td>
		<td>Score</td>
		<td>Status</td>
		<td>Level</td>
		<td>Student ID</td>
		<td>Action</td>
	</tr>
	<% @exams.each do |exam| %>
	<tr>
		<td> <%= exam.title %> </td>
		<td> <%= exam.mapel %> </td>
		<td> <%= exam.duration %> Minutes</td>
		<td> <%= exam.nilai %> </td>
		<td> <%= exam.status %> </td>
		<td> <%= exam.level %> </td>
		<td> <%= exam.student_id %> </td>
		<td> <%= link_to 'Detail', exam_path(exam) %> || <%= link_to 'Edit', edit_exam_path(exam) %> || <%= link_to 'Delete', exam_path(exam), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
	</tr>
	<% end %>
</table>
<%= link_to 'New Data!', new_exam_path %>

app/views/exams/new.html.erb
<%= form_for(@exam) do |e| %>
	<%= e.label :title %></br>
	<%= e.text_field :title %></br>

	<%= e.label :subjects %></br>
	<%= e.text_field :mapel %></br>

	<%= e.label :duration %></br>
	<%= e.text_field :duration %></br>

	<%= e.label :score %></br>
	<%= e.text_field :nilai %></br>

	<%= e.label :status %></br>
	<%= e.text_field :status %></br>

	<%= e.label :level %></br>
	<%= e.text_field :level %></br>

	<%= e.label :student_id %></br>
	<%= e.text_field :student_id %></br>

	<%= e.submit %>
<% end %>

app/views/exams/show.html.erb
<% if flash[:notice].present? %>
	<%= flash[:notice] %>
<% end %>
</br>
Title : <%= @exam.title %> </br>
Subjects : <%= @exam.mapel %> </br>
Duration : <%= @exam.duration %> </br>
Score : <%= @exam.nilai %> </br>
Status : <%= @exam.status %> </br>
Level : <%= @exam.level %> </br>
Student ID: <%= @exam.student_id %> </br>

app/views/payments/edit.html.erb
<%= form_for(@payment) do |pay| %>
	<%= pay.label :id_transaction %></br>
	<%= pay.text_field :id_transaction %></br>

	<%= pay.label :status %></br>
	<%= pay.text_field :status %></br>

	<%= pay.label :upload %></br>
	<%= pay.text_field :upload %></br>

	<%= pay.submit %>
<% end %>

app/views/payments/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %>
</br>
<table>
	<tr>
		<td>ID Transaction</td>
		<td>Status</td>
		<td>Upload</td>
		<td>Action</td>
	</tr>
	<% @payments.each do |payment| %>
	<tr>
		<td> <%= payment.id_transaction %> </td>
		<td> <%= payment.status %> </td>
		<td> <%= payment.upload %> </td>
		<td> <%= link_to 'Detail', payment_path(payment) %> || <%= link_to 'Edit', edit_payment_path(payment) %> || <%= link_to 'Delete', payment_path(payment), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
	</tr>
	<% end %>
</table>
<%= link_to 'New Data!', new_payment_path %>

app/views/payments/new.html.erb
<%= form_for(@payment) do |pay| %>
	<%= pay.label :id_transaction %></br>
	<%= pay.text_field :id_transaction %></br>

	<%= pay.label :status %></br>
	<%= pay.text_field :status %></br>

	<%= pay.label :upload %></br>
	<%= pay.text_field :upload %></br>

	<%= pay.submit %>
<% end %>

app/views/payments/show.html.erb
<% if flash[:notice].present? %>
	<%= flash[:notice] %>
<% end %>
</br>
ID Transaction : <%= @payment.id_transaction %> </br>
Status : <%= @payment.status %> </br>
Upload : <%= @payment.upload %> </br>

app/views/pockets/edit.html.erb
<%= form_for(@pocket) do |poc| %>
	<%= poc.label :balance %></br>
	<%= poc.text_field :balance %></br>

	<%= poc.label :student_id %></br>
	<%= poc.text_field :student_id %></br>

	<%= poc.label :teacher_id %></br>
	<%= poc.text_field :teacher_id %></br>

	<%= poc.submit %>
<% end %>

app/views/pockets/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %>
</br>
<table>
	<tr>
		<td>Balance</td>
		<td>ID Student</td>
		<td>ID Teacher</td>
		<td>Action</td>
	</tr>
	<% @pockets.each do |pocket| %>
	<tr>
		<td> <%= pocket.balance %> </td>
		<td> <%= pocket.student_id %> </td>
		<td> <%= pocket.teacher_id %> </td>
		<td> <%= link_to 'Detail', pocket_path(pocket) %> || <%= link_to 'Edit', edit_pocket_path(pocket) %> || <%= link_to 'Delete', pocket_path(pocket), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
	</tr>
	<% end %>
</table>
<%= link_to 'New Data!', new_pocket_path %>

app/views/pockets/new.html.erb
<%= form_for(@pocket) do |poc| %>
	<%= poc.label :balance %></br>
	<%= poc.text_field :balance %></br>

	<%= poc.label :student_id %></br>
	<%= poc.text_field :student_id %></br>

	<%= poc.label :teacher_id %></br>
	<%= poc.text_field :teacher_id %></br>

	<%= poc.submit %>
<% end %>

app/views/pockets/show.html.erb
<% if flash[:notice].present? %>
	<%= flash[:notice] %>
<% end %>
</br>
Balance : <%= @pocket.balance %> </br>
ID Student : <%= @pocket.student_id %> </br>
ID Teacher : <%= @pocket.teacher_id %> </br>

app/views/reports/edit.html.erb
<%= form_for(@report) do |r| %>
	<%= r.label :title %></br>
	<%= r.text_field :title %></br>

	<%= r.label :nilai %></br>
	<%= r.text_field :nilai %></br>

	<%= r.label :mapel %></br>
	<%= r.text_field :mapel %></br>

	<%= r.label :student_id %></br>
	<%= r.text_field :student_id %></br>

	<%= r.label :teacher_id %></br>
	<%= r.text_field :teacher_id %></br>

	<%= r.label :date %></br>
	<%= r.text_field :date %></br>

	<%= r.submit %>
<% end %>

app/views/reports/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %>
</br>
<table>
	<tr>
		<td>Title</td>
		<td>Score</td>
		<td>Subject</td>
		<td>Title</td>
		<td>ID Student</td>
		<td>ID Teacher</td>
		<td>Date</td>
	</tr>
	<% @reports.each do |report| %>
	<tr>
		<td> <%= report.title %> </td>
		<td> <%= report.nilai %> </td>
		<td> <%= report.mapel %> </td>
		<td> <%= report.student_id %> </td>
		<td> <%= report.teacher_id %> </td>
		<td> <%= report.date %> </td>
		<td> <%= link_to 'Detail', report_path(report) %> || <%= link_to 'Edit', edit_report_path(report) %> || <%= link_to 'Delete', report_path(report), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
	</tr>
	<% end %>
</table>
<%= link_to 'New Data!', new_report_path %>

app/views/reports/new.html.erb
<%= form_for(@report) do |r| %>
	<%= r.label :title %></br>
	<%= r.text_field :title %></br>

	<%= r.label :nilai %></br>
	<%= r.text_field :nilai %></br>

	<%= r.label :mapel %></br>
	<%= r.text_field :mapel %></br>

	<%= r.label :student_id %></br>
	<%= r.text_field :student_id %></br>

	<%= r.label :teacher_id %></br>
	<%= r.text_field :teacher_id %></br>

	<%= r.label :date %></br>
	<%= r.text_field :date %></br>

	<%= r.submit %>
<% end %>

app/views/reports/show.html.erb
<% if flash[:notice].present? %>
	<%= flash[:notice] %>
<% end %>
</br>
Title : <%= @report.title %> </br>
Score : <%= @report.nilai %> </br>
Subjects : <%= @report.mapel %> </br>
ID Student : <%= @report.student_id %> </br>
ID Teacher : <%= @report.teacher_id %> </br>
Date : <%= @report.date %> </br>

app/views/students/edit.html.erb
<%= form_for(@student) do |s| %>
	<%= s.label :name %></br>
	<%= s.text_field :name %></br>

	<%= s.label :username %></br>
	<%= s.text_field :username %></br>

	<%= s.label :age %></br>
	<%= s.text_field :age %></br>

	<%= s.label :class %></br>
	<%= s.text_field :rombel %></br>

	<%= s.label :address %></br>
	<%= s.text_field :address %></br>

	<%= s.label :city %></br>
	<%= s.text_field :city %></br>

	<%= s.label :nik %></br>
	<%= s.text_field :nik %></br>

	<%= s.submit %>
<% end %>

app/views/students/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %>
</br>
<table>
	<tr>
		<td>Name</td>
		<td>Username</td>
		<td>Age</td>
		<td>Class</td>
		<td>Address</td>
		<td>City</td>
		<td>NIK</td>
		<td>Action</td>
	</tr>
	<% @students.each do |student| %>
	<tr>
		<td> <%= student.name %> </td>
		<td> <%= student.username %> </td>
		<td> <%= student.age %> </td>
		<td> <%= student.rombel %> </td>
		<td> <%= student.address %> </td>
		<td> <%= student.city %> </td>
		<td> <%= student.nik %> </td>
		<td> <%= link_to 'Detail', student_path(student) %> || <%= link_to 'Edit', edit_student_path(student) %> || <%= link_to 'Delete', student_path(student), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
	</tr>
	<% end %>
</table>
<%= link_to 'New Data!', new_student_path %>

app/views/students/new.html.erb
<%= form_for(@student) do |s| %>
	<%= s.label :name %></br>
	<%= s.text_field :name %></br>

	<%= s.label :username %></br>
	<%= s.text_field :username %></br>

	<%= s.label :age %></br>
	<%= s.text_field :age %></br>

	<%= s.label :class %></br>
	<%= s.text_field :rombel %></br>

	<%= s.label :address %></br>
	<%= s.text_field :address %></br>

	<%= s.label :city %></br>
	<%= s.text_field :city %></br>

	<%= s.label :nik %></br>
	<%= s.text_field :nik %></br>

	<%= s.submit %>
<% end %>

app/views/students/show.html.erb
<% if flash[:notice].present? %>
	<%= flash[:notice] %>
<% end %>
</br>
Name : <%= @student.name %> </br>
Username : <%= @student.username %> </br>
Age : <%= @student.age %> </br>
Class : <%= @student.rombel %> </br>
Address : <%= @student.address %> </br>
City : <%= @student.city %> </br>
NIK : <%= @student.nik %> </br>

app/views/teachers/edit.html.erb
<%= form_for(@teacher) do |t| %>
	<%= t.label :nik %></br>
	<%= t.text_field :nik %></br>

	<%= t.label :name %></br>
	<%= t.text_field :name %></br>

	<%= t.label :age %></br>
	<%= t.text_field :age %></br>

	<%= t.label :class %></br>
	<%= t.text_field :rombel %></br>

	<%= t.label :subjects %></br>
	<%= t.text_field :mapel %></br>

	<%= t.submit %>
<% end %>

app/views/teachers/index.html.erb
<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %>
</br>
<table>
	<tr>
		<td>NIK</td>
		<td>Name</td>
		<td>Age</td>
		<td>Class</td>
		<td>Subjects</td>
		<td>Action</td>
	</tr>
	<% @teachers.each do |teacher| %>
	<tr>
		<td> <%= teacher.nik %> </td>
		<td> <%= teacher.name %> </td>
		<td> <%= teacher.age %> </td>
		<td> <%= teacher.rombel %> </td>
		<td> <%= teacher.mapel %> </td>
		<td> <%= link_to 'Detail', teacher_path(teacher) %> || <%= link_to 'Edit', edit_teacher_path(teacher) %> || <%= link_to 'Delete', teacher_path(teacher), method: :delete, data: {confirm: 'Are you sure?'} %> </td>
	</tr>
	<% end %>
</table>
<%= link_to 'New Data!', new_teacher_path %>

app/views/teachers/new.html.erb
<%= form_for(@teacher) do |t| %>
	<%= t.label :nik %></br>
	<%= t.text_field :nik %></br>

	<%= t.label :name %></br>
	<%= t.text_field :name %></br>

	<%= t.label :age %></br>
	<%= t.text_field :age %></br>

	<%= t.label :class %></br>
	<%= t.text_field :rombel %></br>

	<%= t.label :subjects %></br>
	<%= t.text_field :mapel %></br>

	<%= t.submit %>
<% end %>

app/views/teachers/show.html.erb
<% if flash[:notice].present? %>
	<%= flash[:notice] %>
<% end %>
</br>
NIK: <%= @teacher.nik %> </br>
Name : <%= @teacher.name %> </br>
Age : <%= @teacher.age %> </br>
Class : <%= @teacher.rombel %> </br>
Subjects : <%= @teacher.mapel %> </br>